# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.18)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget MAVSDK::mavsdk MAVSDK::mavsdk_action MAVSDK::mavsdk_calibration MAVSDK::mavsdk_camera MAVSDK::mavsdk_failure MAVSDK::mavsdk_follow_me MAVSDK::mavsdk_ftp MAVSDK::mavsdk_geofence MAVSDK::mavsdk_gimbal MAVSDK::mavsdk_info MAVSDK::mavsdk_log_files MAVSDK::mavsdk_manual_control MAVSDK::mavsdk_mavlink_passthrough MAVSDK::mavsdk_mission MAVSDK::mavsdk_mission_raw MAVSDK::mavsdk_mocap MAVSDK::mavsdk_offboard MAVSDK::mavsdk_param MAVSDK::mavsdk_shell MAVSDK::mavsdk_telemetry MAVSDK::mavsdk_tracking_server MAVSDK::mavsdk_server_utility MAVSDK::mavsdk_transponder MAVSDK::mavsdk_tune MAVSDK::mavsdk_server_bin)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target MAVSDK::mavsdk
add_library(MAVSDK::mavsdk STATIC IMPORTED)

set_target_properties(MAVSDK::mavsdk PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:CURL::libcurl>;\$<LINK_ONLY:Threads::Threads>;\$<LINK_ONLY:ws2_32>"
)

# Create imported target MAVSDK::mavsdk_action
add_library(MAVSDK::mavsdk_action STATIC IMPORTED)

set_target_properties(MAVSDK::mavsdk_action PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/mavsdk"
  INTERFACE_LINK_LIBRARIES "MAVSDK::mavsdk"
)

# Create imported target MAVSDK::mavsdk_calibration
add_library(MAVSDK::mavsdk_calibration STATIC IMPORTED)

set_target_properties(MAVSDK::mavsdk_calibration PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/mavsdk"
  INTERFACE_LINK_LIBRARIES "MAVSDK::mavsdk"
)

# Create imported target MAVSDK::mavsdk_camera
add_library(MAVSDK::mavsdk_camera STATIC IMPORTED)

set_target_properties(MAVSDK::mavsdk_camera PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/mavsdk"
  INTERFACE_LINK_LIBRARIES "MAVSDK::mavsdk;\$<LINK_ONLY:tinyxml2::tinyxml2>;\$<LINK_ONLY:CURL::libcurl>"
)

# Create imported target MAVSDK::mavsdk_failure
add_library(MAVSDK::mavsdk_failure STATIC IMPORTED)

set_target_properties(MAVSDK::mavsdk_failure PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/mavsdk"
  INTERFACE_LINK_LIBRARIES "MAVSDK::mavsdk"
)

# Create imported target MAVSDK::mavsdk_follow_me
add_library(MAVSDK::mavsdk_follow_me STATIC IMPORTED)

set_target_properties(MAVSDK::mavsdk_follow_me PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/mavsdk"
  INTERFACE_LINK_LIBRARIES "MAVSDK::mavsdk"
)

# Create imported target MAVSDK::mavsdk_ftp
add_library(MAVSDK::mavsdk_ftp STATIC IMPORTED)

set_target_properties(MAVSDK::mavsdk_ftp PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/mavsdk"
  INTERFACE_LINK_LIBRARIES "MAVSDK::mavsdk"
)

# Create imported target MAVSDK::mavsdk_geofence
add_library(MAVSDK::mavsdk_geofence STATIC IMPORTED)

set_target_properties(MAVSDK::mavsdk_geofence PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/mavsdk"
  INTERFACE_LINK_LIBRARIES "MAVSDK::mavsdk"
)

# Create imported target MAVSDK::mavsdk_gimbal
add_library(MAVSDK::mavsdk_gimbal STATIC IMPORTED)

set_target_properties(MAVSDK::mavsdk_gimbal PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/mavsdk"
  INTERFACE_LINK_LIBRARIES "MAVSDK::mavsdk"
)

# Create imported target MAVSDK::mavsdk_info
add_library(MAVSDK::mavsdk_info STATIC IMPORTED)

set_target_properties(MAVSDK::mavsdk_info PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/mavsdk"
  INTERFACE_LINK_LIBRARIES "MAVSDK::mavsdk"
)

# Create imported target MAVSDK::mavsdk_log_files
add_library(MAVSDK::mavsdk_log_files STATIC IMPORTED)

set_target_properties(MAVSDK::mavsdk_log_files PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/mavsdk"
  INTERFACE_LINK_LIBRARIES "MAVSDK::mavsdk"
)

# Create imported target MAVSDK::mavsdk_manual_control
add_library(MAVSDK::mavsdk_manual_control STATIC IMPORTED)

set_target_properties(MAVSDK::mavsdk_manual_control PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/mavsdk"
  INTERFACE_LINK_LIBRARIES "MAVSDK::mavsdk"
)

# Create imported target MAVSDK::mavsdk_mavlink_passthrough
add_library(MAVSDK::mavsdk_mavlink_passthrough STATIC IMPORTED)

set_target_properties(MAVSDK::mavsdk_mavlink_passthrough PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/mavsdk"
  INTERFACE_LINK_LIBRARIES "MAVSDK::mavsdk"
)

# Create imported target MAVSDK::mavsdk_mission
add_library(MAVSDK::mavsdk_mission STATIC IMPORTED)

set_target_properties(MAVSDK::mavsdk_mission PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/mavsdk"
  INTERFACE_LINK_LIBRARIES "MAVSDK::mavsdk;\$<LINK_ONLY:JsonCpp::jsoncpp>"
)

# Create imported target MAVSDK::mavsdk_mission_raw
add_library(MAVSDK::mavsdk_mission_raw STATIC IMPORTED)

set_target_properties(MAVSDK::mavsdk_mission_raw PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/mavsdk"
  INTERFACE_LINK_LIBRARIES "MAVSDK::mavsdk;\$<LINK_ONLY:JsonCpp::jsoncpp>"
)

# Create imported target MAVSDK::mavsdk_mocap
add_library(MAVSDK::mavsdk_mocap STATIC IMPORTED)

set_target_properties(MAVSDK::mavsdk_mocap PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/mavsdk"
  INTERFACE_LINK_LIBRARIES "MAVSDK::mavsdk"
)

# Create imported target MAVSDK::mavsdk_offboard
add_library(MAVSDK::mavsdk_offboard STATIC IMPORTED)

set_target_properties(MAVSDK::mavsdk_offboard PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/mavsdk"
  INTERFACE_LINK_LIBRARIES "MAVSDK::mavsdk"
)

# Create imported target MAVSDK::mavsdk_param
add_library(MAVSDK::mavsdk_param STATIC IMPORTED)

set_target_properties(MAVSDK::mavsdk_param PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/mavsdk"
  INTERFACE_LINK_LIBRARIES "MAVSDK::mavsdk"
)

# Create imported target MAVSDK::mavsdk_shell
add_library(MAVSDK::mavsdk_shell STATIC IMPORTED)

set_target_properties(MAVSDK::mavsdk_shell PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/mavsdk"
  INTERFACE_LINK_LIBRARIES "MAVSDK::mavsdk"
)

# Create imported target MAVSDK::mavsdk_telemetry
add_library(MAVSDK::mavsdk_telemetry STATIC IMPORTED)

set_target_properties(MAVSDK::mavsdk_telemetry PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/mavsdk"
  INTERFACE_LINK_LIBRARIES "MAVSDK::mavsdk"
)

# Create imported target MAVSDK::mavsdk_tracking_server
add_library(MAVSDK::mavsdk_tracking_server STATIC IMPORTED)

set_target_properties(MAVSDK::mavsdk_tracking_server PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/mavsdk"
  INTERFACE_LINK_LIBRARIES "MAVSDK::mavsdk"
)

# Create imported target MAVSDK::mavsdk_server_utility
add_library(MAVSDK::mavsdk_server_utility STATIC IMPORTED)

set_target_properties(MAVSDK::mavsdk_server_utility PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/mavsdk"
  INTERFACE_LINK_LIBRARIES "MAVSDK::mavsdk"
)

# Create imported target MAVSDK::mavsdk_transponder
add_library(MAVSDK::mavsdk_transponder STATIC IMPORTED)

set_target_properties(MAVSDK::mavsdk_transponder PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/mavsdk"
  INTERFACE_LINK_LIBRARIES "MAVSDK::mavsdk"
)

# Create imported target MAVSDK::mavsdk_tune
add_library(MAVSDK::mavsdk_tune STATIC IMPORTED)

set_target_properties(MAVSDK::mavsdk_tune PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/mavsdk"
  INTERFACE_LINK_LIBRARIES "MAVSDK::mavsdk"
)

# Create imported target MAVSDK::mavsdk_server_bin
add_executable(MAVSDK::mavsdk_server_bin IMPORTED)

if(CMAKE_VERSION VERSION_LESS 2.8.12)
  message(FATAL_ERROR "This file relies on consumers using CMake 2.8.12 or greater.")
endif()

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/MAVSDKTargets-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
